name: Package CI

on:
  - push
  - pull_request

jobs:
  test:
    name: Package CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: julia-actions/setup-julia@latest
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
